---
crio_versioned_pkg:
  "1.23":
    - "cri-o-1.23.*"
  "1.22":
    - "cri-o-1.22.*"
  "1.21":
    - "cri-o-1.21.*"

default_crio_packages: "{{ [ crio_versioned_pkg[crio_version], 'oci-systemd-hook' ] }}"

crio_packages: "{{ redhat_crio_packages | default(default_crio_packages) }}"
